########## HTTP encoding Configuration ##########
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  shutdown: graceful
spring:
  application:
    name: data-analysis
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
### Logging ###
logging:
  level:
    com.zaxxer.hikari: debug
    org.hibernate.sql: debug




